blueprint:
  name: External sensor for Aqara TRV
  description: Synchronise external temperature sensor with Aqara TRV
  domain: automation
  
  input:
    sensor_selector:
      name: Internal/external selector
      selector:
        entity:
          filter:
            - intergraion: mqtt
              domain: select

    temp_sensor:
      name: External sensor to synchronise
      selector:
        entity:
          domain: sensor
          device_class: temperature
    aqara_trv:
      name: Aqara TRV
      selector:
        entity:
          filter:
            - intergraion: mqtt
              domain: number

mode: single
max_exceeded: silent

triggers:
  - trigger: state
    entity_id: !input "temp_sensor"
    
conditions: []
actions:
  - if:
      - condition: or
        conditions:
          - condition: state
            entity_id: !input "temp_sensor"
            state: unknown
          - condition: state
            entity_id: !input "temp_sensor"
            state: unavailable
    then:
      - action: select.select_option
        metadata: {}
        data:
          option: internal
        target:
          entity_id: !input "sensor_selector"
    else:
      - if:
          - condition: state
            entity_id: !input "sensor_selector"
            state: internal
        then:
          - action: select.select_option
            metadata: {}
            data:
              option: external
            target:
              entity_id: !input "sensor_selector"
      - action: number.set_value
        metadata: {}
        data:
          value: "{{states(temp_sensor) | float (25)}}"
        target:
          entity_id: !input "aqara_trv"
