blueprint:
  name: External sensor for Aqara TRV
  description: Synchronise external temperature sensor with Aqara TRV
  domain: automation

  input:
    sensor_selector:
      name: Internal/external selector
      selector:
        entity:
          domain: select
    temp_sensor:
      name: External sensor to synchronise
      selector:
        entity:
          domain: sensor
          device_class: temperature
    climate:
      name: Aqara TRV
      selector:
        entity:
          domain: climate

mode: single
max_exceeded: silent

triggers:
  - trigger: state
    entity_id: !input "temp_sensor"
    
conditions: []
actions:
  - action: select.select_option
    metadata: {}
    data:
      option: external
    target:
      entity_id: !input "sensor_selector"

  - action: number.set_value
    metadata: {}
    data:
      value: "{{states(temp_sensor) | float (0)}}"
    target:
      entity_id: !input "climate"

