blueprint:
  name: External temperature sensor for Aqara TRV
  description: Synchronise external temperature sensor with Aqara TRV
  domain: automation

  input:
    temp_sensor:
      name: External sensor to synchronise
      selector:
        entity:
          domain: sensor
          device_class: temperature
    climate:
      name: Aqara TRV
      selector:
        entity:
          domain: climate

mode: single
max_exceeded: silent

triggers:
  - trigger: state
    entity_id: !input "temp_sensor"
    
conditions: []
actions:
  - action: select.select_option
    metadata: {}
    data:
      option: external
    target:
      entity_id: {{climate}}_sensor

  - action: number.set_value
    metadata: {}
    data:
      value: "{{trigger.to_state}}"
    target:
      entity_id: !input "climate"

