blueprint:
  name: Synchronize lights without group
  description: Script checking if any light is on and turning them all off, or turning
    them all on if none are on.
  domain: script
sequence:
  - if:
      - condition: template
        value_template: "{{inclusion_mode}}"
    then:
      - if:
          - condition: template
            value_template: >-
              {{ lights | map('states') | select('equalto', 'off') | list |
              count > 0 }}
        then:
          - action: light.turn_on
            metadata: {}
            data: {}
            target:
              entity_id: "{{lights}}"
        else:
          - action: light.turn_off
            metadata: {}
            data: {}
            target:
              entity_id: "{{lights}}"
    else:
      - if:
          - condition: template
            value_template: >-
              {{ lights | map('states') | select('equalto', 'on') | list | count
              > 0 }}
        then:
          - action: light.turn_off
            metadata: {}
            data: {}
            target:
              entity_id: "{{lights}}"
        else:
          - action: light.turn_on
            metadata: {}
            data: {}
            target:
              entity_id: "{{lights}}"
fields:
  lights:
    name: Lights to synchronise
    required: true
    selector:
      entity:
        domain: light
        multiple: true
  inclusion_mode:
    selector:
      boolean: {}
    name: Inclusion mode
    description: If inclusion is turned on lights will be synchronized to ON if any is lit.
    required: true
    default: false
