blueprint:
  name: Wyłącz światła jeśli któreś jest włączone
  description: Skrypt sprawdza, czy którekolwiek światło z listy jest włączone i jeśli tak, wyłącza je wszystkie.
  domain: script
  input:
    lights:
      name: Światła
      description: Wybierz światła do sprawdzenia i wyłączenia
      selector:
        entity:
          multiple: true
          domain: light

sequence:
  - variables:
      lights_on: >
        {{ iif(lights is string, [lights], lights)
           | select('is_state', 'on')
           | list }}

  - choose:
      - conditions: "{{ lights_on | count > 0 }}"
        sequence:
          - service: light.turn_off
            target:
              entity_id: "{{ lights_on }}"
