blueprint:
  name: synchronize lights script
  description: Script checking if any light is on and turning them all off, or turning them all on if none are on.
  domain: script
  input:
    lights:
      name: Lights to synchronize
      description: list of `light` entities to synchronize
      selector:
        target:
          entity:
            domain: light
sequence:
  - if:
      - condition: template
        value_template: >-
          {{ lights | map('states') | select('equalto', 'on') | list | count > 0
          }}
    then:
      - action: light.turn_off
        metadata: {}
        data: {}
        target:
          entity_id: !input lights
    else:
      - action: light.turn_on
        metadata: {}
        data: {}
        target:
          entity_id: !input lights
