blueprint:
  name: Synchronize lights without group
  description: Script checking if any light is on and turning them all off, or turning them all on if none are on.
  domain: script
  input:
    lights:
      name: Lights to synchronize
      description: list of `light` entities to synchronize
      selector:
        entity:
          filter:
            domain: light
          multiple: true
sequence:

  - variables:
      target_entities: >-
        {{lights.entity_id if lights.entity_id is list else []}}
  - if:
      - condition: template
        value_template: >-
          {{ target_entities | map('states') | select('equalto', 'on') | list | count > 0
          }}
    then:
      - action: light.turn_off
        metadata: {}
        data: {}
        target:
          entity_id: !input lights
    else:
      - action: light.turn_on
        metadata: {}
        data: {}
        target: 
          entity_id: !input lights
